/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

// Import all the nessassary classes from model class
// Import from components from awt and java swing 
import model.UserList;
import java.awt.CardLayout;
import javax.swing.JPanel;
import model.User;

public class MainJframe2 extends javax.swing.JFrame {
// Intiatialization of the User and UserList  class. 
// Intiatialization of the adminuserjpanel to which the admin button points to 
    User user;
    private UserList userlist;
    adminuserjpanel panel;
    
    
    public MainJframe2() {
        initComponents();
        // referring to the instance of the User and UserList Classes 
        // An instance of a class is a template of the class for example an instance of the User class would contain details of a particular user
        // Another instance would contain another users details 
        
        this.user=user;
        this.userlist=new UserList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        Panel1 = new javax.swing.JPanel();
        LoginBtn = new javax.swing.JButton();
        AdminBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DisplayScreen = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        Panel1.setBackground(new java.awt.Color(255, 204, 204));

        LoginBtn.setText("Login");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        AdminBtn.setText("Admin");
        AdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Northeastern University");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(LoginBtn)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(AdminBtn)
                .addGap(55, 55, 55))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginBtn)
                    .addComponent(AdminBtn)
                    .addComponent(jLabel1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(Panel1);

        DisplayScreen.setBackground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout DisplayScreenLayout = new javax.swing.GroupLayout(DisplayScreen);
        DisplayScreen.setLayout(DisplayScreenLayout);
        DisplayScreenLayout.setHorizontalGroup(
            DisplayScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );
        DisplayScreenLayout.setVerticalGroup(
            DisplayScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(DisplayScreen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // All the parts in Blue are unmodifiable in the code 
        // you can only modify them in the design portion 
        // refer to the constructor in the LoginJpanel panel 
        // make sure the arguments match
        // the "JPanelDataType" written is small words signifies that Display Screen is just an instance of the JPanel Datatype
        LoginJPanel panel=new LoginJPanel(DisplayScreen,user);
        // code to facilitate the display of LoginJPanel on a particular Panel in the MainJFrame2
        // panel refers to the instance of LoginJPanel
        DisplayScreen.add("LoginJPanel",panel);
        CardLayout layout=(CardLayout)DisplayScreen.getLayout();
        layout.next(DisplayScreen);
        
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void AdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBtnActionPerformed
        adminuserjpanel panel=new adminuserjpanel(DisplayScreen,userlist);
        DisplayScreen.add("AdminJPanel",panel);
        CardLayout layout=(CardLayout)DisplayScreen.getLayout();
        layout.next(DisplayScreen);
    }//GEN-LAST:event_AdminBtnActionPerformed

    
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBtn;
    private javax.swing.JPanel DisplayScreen;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JPanel Panel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
